import AuthProvider from './components/AuthProvider/AuthProvider'
import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
},) {
  return (
    <html>
      <body>
          {/* <AuthProvider> */}
            <Header />
            {children}
            <Footer/>
          {/* </AuthProvider> */}
      </body>
    </html>
  )
}
